[package]
name = "backend_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.8.0"
chrono = "0.4.38"
diesel = { version = "2.2.1", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
