// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;
use serde::Serialize;


#[derive(Serialize,Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub password: String,
    pub email: Option<String>,
}

