[package]
name = "gpui_test"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
